_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/ppyolo_tiny.yml',
  './_base_/optimizer_650e.yml',
  './_base_/ppyolo_tiny_reader.yml',
]

snapshot_epoch: 1
weights: output/ppyolo_tiny_650e_coco/model_final

TestDataset:
  !ImageFolder
  anno_path: null
  with_crowd: false
  sample_transforms:
    - DecodeImage:
      to_rgb: true
  batch_transforms:
    - NormalizeImage:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: true
    - Permute:
      to_bgr: false
